# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_name', models.CharField(max_length=200, verbose_name='Mod name')),
                ('version', models.CharField(max_length=10, verbose_name='Mod version')),
                ('author', models.CharField(max_length=200, verbose_name='Mod author')),
                ('url', models.URLField(blank=True, verbose_name='Link to mod website')),
            ],
        ),
        migrations.CreateModel(
            name='Modpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modpack_name', models.CharField(max_length=200, verbose_name='Modpack Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description of modpack')),
                ('slug', models.SlugField()),
                ('mods', models.ManyToManyField(blank=True, to='modpacks.Mod', verbose_name='Included mods')),
            ],
        ),
    ]
