# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modpacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mod author'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='version',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mod version'),
        ),
    ]
