# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modpacks', '0002_auto_20160914_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='modpack',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='Screenshot'),
        ),
    ]
