# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(max_length=50, verbose_name='In-Game Account Name')),
                ('status', models.CharField(blank=True, max_length=1, verbose_name='Player Status')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
