# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(max_length=50, unique=True, verbose_name='in-game account name')),
                ('status', models.CharField(choices=[('y', 'Approved'), ('n', 'Denied'), ('?', 'Pending')], default='?', max_length=1, verbose_name='player status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('uuid', models.UUIDField(default='00000000000000000000000000000000', verbose_name='Mojang UUID')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedPlayer',
            fields=[
            ],
            options={
                'verbose_name': 'approved player',
                'proxy': True,
            },
            bases=('whitelist.player',),
        ),
        migrations.CreateModel(
            name='DeniedPlayer',
            fields=[
            ],
            options={
                'verbose_name': 'denied player',
                'proxy': True,
            },
            bases=('whitelist.player',),
        ),
        migrations.CreateModel(
            name='PendingPlayer',
            fields=[
            ],
            options={
                'verbose_name': 'pending player',
                'proxy': True,
            },
            bases=('whitelist.player',),
        ),
    ]
