# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedPlayer',
            fields=[
            ],
            options={
                'verbose_name': 'approved player',
                'proxy': True,
            },
            bases=('whitelist.player',),
        ),
        migrations.CreateModel(
            name='DeniedPlayer',
            fields=[
            ],
            options={
                'verbose_name': 'denied player',
                'proxy': True,
            },
            bases=('whitelist.player',),
        ),
        migrations.CreateModel(
            name='PendingPlayer',
            fields=[
            ],
            options={
                'verbose_name': 'pending player',
                'proxy': True,
            },
            bases=('whitelist.player',),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ign',
            field=models.CharField(max_length=50, unique=True, verbose_name='In-Game Account Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(default='?', max_length=1, verbose_name='Player Status'),
        ),
    ]
