# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0002_auto_20160927_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('y', 'Approved'), ('n', 'Denied'), ('?', 'Pending')], default='?', max_length=1, verbose_name='Player Status'),
        ),
    ]
