# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0003_auto_20160927_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(blank=True, default='00000000000000000000000000000000', verbose_name='Mojang UUID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ign',
            field=models.CharField(max_length=50, unique=True, verbose_name='in-game account name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('y', 'Approved'), ('n', 'Denied'), ('?', 'Pending')], default='?', max_length=1, verbose_name='player status'),
        ),
    ]
