# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0004_auto_20160928_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default='00000000000000000000000000000000', verbose_name='Mojang UUID'),
        ),
    ]
